name: Python Non-Cont Build
 
on: 

 workflow_dispatch
 
jobs:

  Py_Build:

   runs-on: ubuntu-latest

   steps:

     - name: Checkout

       uses: actions/checkout@v6.0.2

     - name: setup/install python dependiencies

       uses: actions/setup-python@v6.2.0

       with:

        run: python -m pip install            # installing dependencies

     - name: .py build                            

       run: |

        python -m py_compile src/main.py          # Byte-compiles .py â†’ .pyc (optional)

        echo "Python build successful"

     - name: publish artifact

       uses: actions/upload-artifact@v6.0.0

       with:

        name: python package

        mkdir: staging

        path: staging
